name: 🧼 Hourly Detailing Lead Agent

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync-agent:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install openai pyyaml

      - name: Run detailing lead agent
        run: python detailing-leads-agent.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
